Added IngredientsTableView and IngredientsTableViewCell
KhazovDV/galleyRecipe pull request #10
Opened 2023-01-31 19:38 UTC by philippzeppelin

2023-01-31 20:15 UTC, hakimovkam approved these changes

2023-01-31 20:15 UTC, hakimovkam commented on galleyRecipe/SceneDelegate.swift
> +        window?.rootViewController = IngredientsViewController()
Тут на будущее ,наверное, нужно было обратно вернуть к tabBarColler

2023-01-31 20:15 UTC, hakimovkam commented on galleyRecipe/View/Ingredients/IngredientsViewController.swift
> +    private let idOptionalTableViewCell = "idOptionalTableViewCell"
identifier наверное лучше прописывать внутри класса cell. 
если я захочу переиспользовать ячейку, то мне проще будет выдернуть прям из класса ячейки.

2023-02-01 14:57 UTC, Ramiz69 requested changes

2023-02-01 14:57 UTC, Ramiz69 commented on galleyRecipe/View/Assets.xcassets/CellItems/Pasta.imageset/Contents.json
> +      "idiom" : "universal",
png -> pdf

2023-02-01 14:57 UTC, Ramiz69 commented on galleyRecipe/View/Ingredients/IngredientsTableViewCell.swift
> +class IngredientsTableViewCell: UITableViewCell {
final

2023-02-01 14:57 UTC, Ramiz69 commented on galleyRecipe/View/Ingredients/IngredientsTableViewCell.swift
> +        label.text = "400 g"
а если будет локализация, а если данные будут с бека приходить?
Лучше создать модель ```
struct Italio {
 let name: String
 let weight: String / Double
}
```
и в коде у тебя label.text = model.weight

2023-02-01 14:57 UTC, Ramiz69 commented on galleyRecipe/View/Ingredients/IngredientsTableViewCell.swift
> +    required init?(coder: NSCoder) {
@available(*, unavailable)

2023-02-01 14:57 UTC, Ramiz69 commented on galleyRecipe/View/Ingredients/IngredientsViewController.swift
> +class IngredientsViewController: UIViewController {
final

2023-02-01 15:52 UTC, hakimovkam commented on galleyRecipe/View/Ingredients/IngredientsTableViewCell.swift
> +        label.text = "400 g"
Моделька пока еще в процессе, пока просто как заглушки для вёрстки экрана. Как сетевой слой и модели будут готовы сразу всё внедрим!

2023-02-01 15:53 UTC, hakimovkam commented on galleyRecipe/View/Ingredients/IngredientsTableViewCell.swift
> +        label.text = "400 g"
> а если будет локализация, а если данные будут с бека приходить? Лучше создать модель ``` struct Italio { let name: String let weight: String / Double }
> 
> ```
> и в коде у тебя label.text = model.weight
> ```

Моделька пока еще в процессе, пока просто как заглушки для вёрстки экрана. Как сетевой слой и модели будут готовы сразу всё внедрим!

2023-02-01 15:53 UTC, hakimovkam commented on galleyRecipe/View/Assets.xcassets/CellItems/Pasta.imageset/Contents.json
> +      "idiom" : "universal",
> png -> pdf

а в чем существенный минус png перед pdf?

2023-02-01 15:56 UTC, Ramiz69 commented on galleyRecipe/View/Assets.xcassets/CellItems/Pasta.imageset/Contents.json
> +      "idiom" : "universal",
pdf - вектор + 3 файла vs 1 файл

2023-02-01 16:20 UTC, hakimovkam commented on galleyRecipe/View/Assets.xcassets/CellItems/Pasta.imageset/Contents.json
> +      "idiom" : "universal",
> pdf - вектор + 3 файла vs 1 файл

я слышал, что Xcode под капотом векторные изображения всё равно перегоняет в растровые изображения и  при использовании векторных изображений используется больше ресурсов нежели когда мы используем заготовленные растровые

2023-02-06 10:00 UTC, RafiaSafina approved these changes

2023-02-06 18:55 UTC, philippzeppelin commented on galleyRecipe/View/Ingredients/IngredientsTableViewCell.swift
> +    required init?(coder: NSCoder) {
А зачем так делать?

2023-02-12 09:57 UTC, merged