Routing
KhazovDV/galleyRecipe pull request #12
Opened 2023-02-01 16:06 UTC by hakimovkam

Добавил в приложение "зарисовку" роутинга на последующие экраны. К экранам FavoriteViewController, TimerViewController, TimerListViewController и IngredientViewController создал presenter. В Router добавил функции перехода ко следующим экранам. В builder добавил функции, которые возвращают созданные экраны. В будущем когда будет сетевой слой через презентеры и роутинг будут опрокидываться модельки.

2023-02-02 11:17 UTC, Ramiz69 requested changes

2023-02-02 11:17 UTC, Ramiz69 commented on galleyRecipe/Extension/UIExtension.swift
>          var checkInt = 0
странный нейминг. Для чего эта переменнная?

2023-02-02 11:17 UTC, Ramiz69 commented on galleyRecipe/Favorites Module/FavoritesViewController.swift
> +        else if (self.lastContentOffset < scrollView.contentOffset.y) {
`} else if {`

2023-02-02 11:17 UTC, Ramiz69 commented on galleyRecipe/Favorites Module/FavoritesViewController.swift
> +        if (self.lastContentOffset > scrollView.contentOffset.y) {
() скоробочки не нужны в swift для условий if else

2023-02-02 11:17 UTC, Ramiz69 commented on galleyRecipe/IngridientModule/IngredientViewController.swift
> +    @objc func backButtonWasPressed() {
```
@objc
func ....
```

2023-02-02 11:17 UTC, Ramiz69 commented on galleyRecipe/IngridientPresenter.swift
> +//    func didUpdate()
комментарии удаляем

2023-02-02 11:19 UTC, hakimovkam commented on galleyRecipe/Extension/UIExtension.swift
>          var checkInt = 0
> странный нейминг. Для чего эта переменнная?

возвращает вьюшку для tableViewHeader

2023-02-02 11:21 UTC, hakimovkam commented on galleyRecipe/IngridientPresenter.swift
> +//    func didUpdate()
> комментарии удаляем

Они пригодятся, когда будут готовы будущие экраны. 
или это не особо этично в разработке оставлять какой-то функционал в виде комментариев для будущего задела?

2023-02-03 06:25 UTC, KhazovDV approved these changes
Approve

2023-02-03 07:58 UTC, philippzeppelin approved these changes
Approve

2023-02-06 10:01 UTC, RafiaSafina approved these changes
approve

2023-02-06 10:28 UTC, d1mka112 commented on galleyRecipe/IngridientPresenter.swift
> +//    func didUpdate()
Если комментарий нужен потом, прям указывайте это // Будет раскомменчено после задачи (Номер задачи) или (Название задачи)

2023-02-12 12:28 UTC, merged