Reworking search view controller
KhazovDV/galleyRecipe pull request #13
Opened 2023-02-03 11:13 UTC by hakimovkam

Доработал экран SeaerchViewController.

2023-02-06 10:02 UTC, RafiaSafina approved these changes
approve

2023-02-06 14:26 UTC, Sixezr requested changes
в целом комменты применимы ко всем файлам, стоит поправить все файлы
+ пр делать меньше желательно

у вас плохой .gitignore, не нужно .DS_Store в репу комиттить

2023-02-06 14:26 UTC, Sixezr commented on galleyRecipe/CustomViews/Extension/UIExtension.swift
> +//    }
лишнее

2023-02-06 14:26 UTC, Sixezr commented on galleyRecipe/CustomViews/ImageConstant.swift
> +    //    static let starOutline = "StarOutline"
не нужно оставлять такие комменты

2023-02-06 14:26 UTC, Sixezr commented on galleyRecipe/CustomViews/UI Elements/CategoryCollectionView.swift
> +class CategoryCollectionView: UICollectionView {
прочитать про `final` и зачем он нужен

2023-02-06 14:26 UTC, Sixezr commented on galleyRecipe/CustomViews/UI Elements/CategoryCollectionView.swift
> +    var nameCategoryArray = ["Soup", "Pasta", "Egg", "Apple", "Orange", "Soup", "Pasta", "Egg", "Apple", "Orange", "Soup", "Pasta", "Egg", "Apple", "Orange"] //testing data
обычно тестовые данные не оставляют во вьюшках, стоит убрать/вынести

2023-02-06 14:26 UTC, Sixezr commented on galleyRecipe/CustomViews/UI Elements/CategoryCollectionView.swift
> +
nit: лишние строки

2023-02-06 14:26 UTC, Sixezr commented on galleyRecipe/CustomViews/UI Elements/CategoryCollectionView.swift
> +//MARK: - Delegate&DataSource
вьюшка не должна быть сама себе делегатом и датасорсом

2023-02-06 14:26 UTC, Sixezr commented on galleyRecipe/CustomViews/UI Elements/ChipsCollectionViewCell.swift
> +class ChipsCollectionViewCell: UICollectionViewCell {
`final`

2023-02-06 14:26 UTC, Sixezr commented on galleyRecipe/CustomViews/UI Elements/ChipsCollectionViewCell.swift
> +    var label: UILabel = {
почему `var`?

2023-02-06 14:26 UTC, Sixezr commented on galleyRecipe/CustomViews/UI Elements/ChipsCollectionViewCell.swift
> +    func addView() {
сделать приватной, извне не должен быть вызов

2023-02-06 14:26 UTC, Sixezr commented on galleyRecipe/CustomViews/UI Elements/ChipsCollectionViewCell.swift
> +    var label: UILabel = {
и сделать приватной

2023-02-06 14:26 UTC, Sixezr commented on galleyRecipe/CustomViews/UI Elements/ChipsCollectionViewCell.swift
> +        label.text = " "
мок данные не стоит пушить в дев

2023-02-06 14:26 UTC, Sixezr commented on galleyRecipe/CustomViews/UI Elements/CountryCollectionView.swift
> +class CountryCollectionView: UICollectionView {
в целом аналогичные комменты, как и по другой коллекции

2023-02-06 14:26 UTC, Sixezr commented on galleyRecipe/Favorites Module/Presenter/FavoritePresenter.swift
> +    func tapOnTheRecipe() {
nit: по неймингу лучше `didTapOn...`

2023-02-06 14:26 UTC, Sixezr commented on galleyRecipe/Favorites Module/View/FavoritesViewController.swift
> +        } else if self.lastContentOffset < scrollView.contentOffset.y {
а если `lastContentOffset == scrollView.contentOffset.y`?

2023-02-06 14:26 UTC, Sixezr commented on galleyRecipe/IngridientModule/Presenter/IngridientPresenter.swift
> +//    func didFailWithError(error: Error)
не нужно оставлять такое

2023-02-06 14:26 UTC, Sixezr commented on galleyRecipe/IngridientModule/Presenter/IngridientPresenter.swift
> +class IngridientPresenter: IngridientViewPresenterProtocol {
`final`

2023-02-06 14:26 UTC, Sixezr commented on galleyRecipe/IngridientModule/View/IngredientViewController.swift
> +    var presenter: IngridientViewPresenterProtocol!
зачем `IngridientViewPresenterProtocol!`? достаточно в ините прокидывать, а у презентера будет слабая ссылка на контролле

2023-02-11 14:02 UTC, Sixezr requested changes

2023-02-11 14:02 UTC, Sixezr commented on galleyRecipe/CustomViews/UI Elements/ChipsCollectionViewCell.swift
> +class ChipsCollectionViewCell: UICollectionViewCell {
забыл добавить

2023-02-11 14:02 UTC, Sixezr commented on galleyRecipe/Favorites Module/Presenter/FavoritePresenter.swift
> +    var view: FavoriteViewProtocol? { get set }
это не надо в протокол презентера, так как должно быть приватное при использовании через протокол

2023-02-11 14:02 UTC, Sixezr commented on galleyRecipe/Favorites Module/Presenter/FavoritePresenter.swift
> +    init(networkService: NetworkServiceProtocol, router: RouterProtocol)
да и в целом инит не выносят в протокол, в этом нет необходиомсти

2023-02-11 14:02 UTC, Sixezr commented on galleyRecipe/Favorites Module/View/FavoritesViewController.swift
> +        } else if self.lastContentOffset == scrollView.contentOffset.y {
можно просто `else`

2023-02-11 14:02 UTC, Sixezr commented on galleyRecipe/IngridientModule/Presenter/IngridientPresenter.swift
> +    var view: IngridientViewProtocol? { get set }
аналогично, не надо в протокол добавлять вьюшку

2023-02-11 14:02 UTC, Sixezr commented on galleyRecipe/IngridientModule/View/IngredientViewController.swift
> +    var presenter: IngridientViewPresenterProtocol
`private let`, через инит потому что

2023-02-11 14:02 UTC, Sixezr commented on galleyRecipe/Routing/Builder.swift
>  class Builder: BuilderProtocol {
тоже можно `final` либо структурой сделать

2023-02-11 14:02 UTC, Sixezr commented on galleyRecipe/TimerModule/Presenter/TimerListPresenter.swift
> +    var view: TimerListViewProtocol? { get set }
аналогино, убрать из протокола

2023-02-11 14:02 UTC, Sixezr commented on galleyRecipe/TimerModule/Presenter/TimerPresenter.swift
> +    var view: TimerViewProtocol? { get set }
и тут

2023-02-11 14:02 UTC, Sixezr commented on galleyRecipe/TimerModule/View/TimerViewController.swift
> +    var presenter: TimerViewPresenterProtocol
`private let`

2023-02-12 11:10 UTC, Sixezr approved these changes

2023-02-12 11:10 UTC, Sixezr commented on galleyRecipe/CustomViews/UI Elements/CustomTableViewCell.swift
> +    func configure(recipeDescription: String, recipeImageName: String) {
nit: можно в модельку обернуть

2023-02-12 11:47 UTC, philippzeppelin approved these changes
Approve

2023-02-12 11:55 UTC, KhazovDV approved these changes
Approve

2023-02-12 12:48 UTC, merged